import type { SiteContent } from '../en'

export const ui: SiteContent['ui'] = {
  skipToContent: 'تخطَّ إلى المحتوى',
  menuOpen: 'فتح القائمة',
  menuClose: 'إغلاق القائمة',
  primaryNavLabel: 'القائمة الرئيسية',
  contactCta: 'تواصل معنا',
  home: 'الرئيسية',
  quote: (text: string) => `«${text}»`,
  listSeparator: '، ',
  breadcrumb: 'مسار التنقل',
  pages: { projects: 'المشاريع', about: 'من نحن', contact: 'اتصل بنا' },
  companyProfile: 'الملف التعريفي (PDF)',
  projectsList: {
    title: 'قائمة المشاريع',
    filterLabel: 'تصفية المشاريع حسب الفئة',
    shown: (n: number) => `عدد المشاريع المعروضة: ${n}`,
    table: { no: 'الرقم', project: 'المشروع', place: 'الموقع', client: 'الجهة المستفيدة' },
  },
  about: {
    visionMissionLabel: 'الرؤية والرسالة',
    valuesTitle: 'قيمنا الأساسية',
    valuesHighlight: 'الأساسية',
    workforce: 'القوى العاملة',
    fleet: 'أسطول المعدات',
    maintenance: 'الورش والصيانة',
  },
  backToProjects: 'جميع المشاريع',
  viewProject: 'تفاصيل المشروع',
  status: { completed: 'منجز', ongoing: 'قيد التنفيذ' },
  projectMeta: {
    category: 'الفئة',
    location: 'الموقع',
    client: 'الجهة / الشريك',
    period: 'المدة',
    status: 'الحالة',
    scope: 'نطاق العمل',
    gallery: 'معرض الصور',
    related: 'مشاريع ذات صلة',
  },
  lightbox: {
    close: 'إغلاق',
    previous: 'الصورة السابقة',
    next: 'الصورة التالية',
    open: 'عرض الصورة',
    counter: (i: number, n: number) => `${i} من ${n}`,
  },
  documents: { download: 'تنزيل PDF', onRequest: 'متاح عند الطلب' },
  footer: {
    quickLinks: 'روابط سريعة',
    services: 'خدماتنا',
    contact: 'التواصل',
    rights: (year: number, legalName: string) => `© ${year} ${legalName}`,
  },
  contact: {
    address: 'العنوان',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    hours: 'ساعات العمل',
    mapTitle: 'خريطة موقع المكتب',
    sectionLabel: 'بيانات التواصل ونموذج المراسلة',
  },
  form: {
    name: 'الاسم الكامل',
    company: 'الشركة',
    email: 'البريد الإلكتروني',
    phone: 'رقم الهاتف',
    service: 'الخدمة المطلوبة',
    servicePlaceholder: 'اختر خدمة',
    serviceOther: 'أخرى / استفسار عام',
    message: 'الرسالة',
    optional: '(اختياري)',
    submit: 'إرسال الرسالة',
    submitting: 'جارٍ الإرسال…',
    honeypot: 'اترك هذا الحقل فارغاً',
    errors: {
      required: 'هذا الحقل مطلوب.',
      email: 'يرجى إدخال بريد إلكتروني صحيح.',
      phone: 'يرجى إدخال رقم هاتف صحيح.',
      messageLength: 'يرجى كتابة 20 حرفاً على الأقل.',
      summary: 'يرجى تصحيح الحقول المحددة.',
    },
    success: {
      title: 'شكراً لك، تم إرسال رسالتك.',
      text: 'سنتواصل معك في أقرب وقت ممكن.',
    },
    mailto: {
      title: 'سيُفتح الآن تطبيق البريد الإلكتروني لديك.',
      text: 'إن لم يُفتح، راسلنا مباشرة على',
    },
    failure: {
      title: 'تعذّر إرسال رسالتك.',
      text: 'يرجى المحاولة مجدداً، أو التواصل معنا عبر الهاتف أو البريد الإلكتروني.',
    },
    again: 'إرسال رسالة أخرى',
  },
  notFound: {
    code: '404',
    title: 'الصفحة غير موجودة',
    text: 'الصفحة التي تبحث عنها غير موجودة أو تم نقلها.',
    cta: 'العودة إلى الرئيسية',
  },
}
